name: DigiWatts
title: DigiWatts
email: erikdmitchell@gmail.com
description: DigiWatts website 0.0.1
baseurl: "" # the subpath of your site, e.g. /blog
url: https://digiwatts.github.io/
twitter_username: erikdmitchell
github_username:  erikdmitchell

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
