name:          DigiWatts
title:         DigiWatts
description:   DigiWatts
url:           https://digiwatts.github.io/
author:
  name:    erikdmitchell
  email:   erikdmitchell@gmail.com
  github:  erikdmitchell
  twitter: erikdmitchell

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass